// AUTO-GENERATED by `npm run compute-markings` — do not edit by hand.
// The canonical minimal-domain marking (cut + developOrder + generatorLoops) per
// triangulation id, read by defineTriangulation. Absent ids fall back to a
// layout-free marking. See src/math/marking.ts.

export type SavedMarking = { developOrder: number[]; generatorLoops: number[][]; cut: number[] };

export const MARKINGS: Record<number, SavedMarking> = {
  1: { developOrder: [15, 5, 7, 14, 8, 2, 0, 1, 10, 11, 6, 4, 12, 13, 9, 3], generatorLoops: [[7, 4, 1, 7], [7, 4, 1, 0, 3, 7]], cut: [65538, 65539, 65543, 131079, 196615] },
  2: { developOrder: [9, 14, 5, 1, 3, 13, 7, 8, 12, 11, 2, 0, 4, 6, 15, 10], generatorLoops: [[6, 2, 1, 6], [4, 2, 1, 4]], cut: [1, 4, 65542, 65540, 262150] },
  3: { developOrder: [14, 12, 7, 8, 11, 9, 2, 0, 4, 6, 15, 13, 5, 1, 3, 10], generatorLoops: [[6, 2, 1, 6], [4, 2, 1, 4]], cut: [1, 4, 65542, 65540, 262150] },
  4: { developOrder: [11, 10, 15, 12, 6, 1, 3, 13, 8, 7, 9, 2, 0, 5, 4, 14], generatorLoops: [[5, 2, 0, 5], [4, 2, 1, 4]], cut: [1, 4, 5, 65541, 65540] },
  5: { developOrder: [10, 6, 1, 3, 14, 9, 8, 12, 2, 0, 5, 13, 15, 7, 11, 4], generatorLoops: [[5, 2, 0, 5], [4, 2, 1, 4]], cut: [1, 4, 5, 65541, 65540] },
  6: { developOrder: [12, 11, 15, 7, 6, 1, 3, 13, 9, 8, 10, 2, 0, 5, 4, 14], generatorLoops: [[5, 2, 0, 5], [4, 2, 1, 4]], cut: [1, 4, 5, 65541, 65540] },
  7: { developOrder: [12, 11, 5, 4, 13, 7, 1, 3, 14, 9, 8, 10, 2, 0, 6, 15], generatorLoops: [[4, 2, 3, 4], [5, 2, 0, 5]], cut: [196613, 196612, 3, 5, 262149] },
};
