/**
 * GENERATED by scripts/compute-markings.mjs — DO NOT EDIT BY HAND.
 *
 * The precomputed marking (developing chart) of each triangulation in eightVertex.ts,
 * keyed by id, in readable vertex/edge/face numbers. A marking is a deterministic function of
 * the triangle list; this file is that function tabulated over the census. Regenerate with
 * `npm run compute-markings` after changing triangulation data.
 */

import type { Marking } from '@core/topology/triangulation.ts';

export const MARKINGS: Record<string, Marking> = {
  'v8-1': { loops: [[7,4,1,7],[7,4,1,0,3,7]], cut: [[1,2],[1,3],[1,7],[2,7],[3,7]], developOrder: [15,5,7,14,8,2,0,1,10,11,6,4,12,13,9,3] },
  'v8-2': { loops: [[6,2,1,6],[4,2,1,4]], cut: [[0,1],[0,4],[1,6],[1,4],[4,6]], developOrder: [9,14,5,1,3,13,7,8,12,11,2,0,4,6,15,10] },
  'v8-3': { loops: [[6,2,1,6],[4,2,1,4]], cut: [[0,1],[0,4],[1,6],[1,4],[4,6]], developOrder: [14,12,7,8,11,9,2,0,4,6,15,13,5,1,3,10] },
  'v8-4': { loops: [[5,2,0,5],[4,2,1,4]], cut: [[0,1],[0,4],[0,5],[1,5],[1,4]], developOrder: [11,10,15,12,6,1,3,13,8,7,9,2,0,5,4,14] },
  'v8-5': { loops: [[5,2,0,5],[4,2,1,4]], cut: [[0,1],[0,4],[0,5],[1,5],[1,4]], developOrder: [10,6,1,3,14,9,8,12,2,0,5,13,15,7,11,4] },
  'v8-6': { loops: [[5,2,0,5],[4,2,1,4]], cut: [[0,1],[0,4],[0,5],[1,5],[1,4]], developOrder: [12,11,15,7,6,1,3,13,9,8,10,2,0,5,4,14] },
  'v8-7': { loops: [[4,2,3,4],[5,2,0,5]], cut: [[3,5],[3,4],[0,3],[0,5],[4,5]], developOrder: [12,11,5,4,13,7,1,3,14,9,8,10,2,0,6,15] },
};
