/**
 * GENERATED by scripts/compute-markings.mjs — DO NOT EDIT BY HAND.
 *
 * The precomputed marking (developing chart) of each triangulation in sevenVertex.ts,
 * keyed by id, in readable vertex/edge/face numbers. A marking is a deterministic function of
 * the triangle list; this file is that function tabulated over the census. Regenerate with
 * `npm run compute-markings` after changing triangulation data.
 */

import type { Marking } from '@core/topology/triangulation.ts';

export const MARKINGS: Record<string, Marking> = {
  'v7-1': { loops: [[6,3,0,6],[6,3,0,2,6]], cut: [[0,1],[1,2],[0,6],[1,6],[2,6]], developOrder: [13,8,9,4,2,0,10,11,7,1,3,5,12,6] },
};
